# Generated by Django 5.1.3 on 2024-12-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description',
            field=models.TextField(default='HI', max_length=500),
            preserve_default=False,
        ),
    ]
