# Generated by Django 5.1.3 on 2024-12-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_user_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Specifications',
            field=models.TextField(max_length=500),
        ),
    ]
