# Generated by Django 5.1.3 on 2024-12-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_user'),
        ('products', '0002_product_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='product',
            name='Rating',
            field=models.FloatField(default=4.5),
            preserve_default=False,
        ),
    ]
