# Generated by Django 5.1.3 on 2024-12-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_user_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
    ]
