# Generated by Django 5.1.3 on 2024-12-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_user_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cart',
        ),
        migrations.AddField(
            model_name='customer',
            name='firstName',
            field=models.CharField(default='Kris', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='lastName',
            field=models.CharField(default='S', max_length=30),
            preserve_default=False,
        ),
    ]
