# Generated by Django 5.1.3 on 2024-12-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_customer_cart_customer_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.ManyToManyField(default=None, to='products.product'),
        ),
    ]
