# Generated by Django 5.1.3 on 2024-12-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_customer_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cart',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
